# This is a basic workflow to help you get started with Actions

name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: print Greeting
        run: echo "Hello, world!"
      - name: print Good bye
        run: echo "Add other actions to build,"
          
